[[main]]
	name = "About"
	url = "/about"
  weight = 1

[[main]]
	name = "Solutions"
  url = "/solutions"
  weight = 1

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 3

[[main]]
  name = "Imprint"
  url = "/imprint"
  weight = 4

[[main]]
  name = "Privacy"
  url = "/privacy"
  weight = 5
