[[main]]
	name = "Über uns"
	url = "/about"
  weight = 1

[[main]]
	name = "Dienstleistungen"
  url = "/solutions"
  weight = 1

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[main]]
  name = "Kontakt"
  url = "/contact"
  weight = 3

[[main]]
  name = "Impressum"
  url = "/imprint"
  weight = 4

[[main]]
  name = "Datenschutz"
  url = "/privacy"
  weight = 5
