[[main]]
	name = "À propos"
	url = "/about"
  weight = 1

[[main]]
	name = "Solutions"
  url = "/solutions"
  weight = 1

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 3

[[main]]
  name = "Impression"
  url = "/imprint"
  weight = 4

[[main]]
  name = "Vie privée"
  url = "/privacy"
  weight = 5
